urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sentry/', include('sentry.web.urls')),
    url(r'^fandjango/', include('fandjango.urls')),

)

urlpatterns += patterns('wootmatch.fbook.views',
    url(r'^$', 'canvas', name='canvas'),
    url(r'^remove-person$', 'remove_person', name='remove_person'),
    #url(r'^remove$', 'remove', name='remove'),
    #url(r'^update-matches$', 'update_matches', name='update_matches'),
    url(r'^change-email$', 'change_email', name='change_email'),
    url(r'^add-person$', 'add_person', name='add_person'),
    url(r'^update-rank$', 'update_rank', name='update_rank'),
    url(r'^deauthorize', 'deauthorize_application'),
    url(r'^accounts/delete','delete_account', name="delete_account"),
    url(r'^request-features', 'request_features',name='request_features'),    
    url(r'^upvote', 'upvote', name='upvote'),
    url(r'^create-msg', 'create_msg', name='create_msg'),
    url(r'^get-msg', 'get_msg', name='get_msg'),
    url(r'test','test')
)

fbook/models.py
from django.db import models
from fandjango.models import User

class Client(models.Model):
    user = models.ForeignKey(User)
    #interests = models.ManyToManyField('self', through='Interest', symmetrical=False, related_name='interest_in')
    likes = models.CharField(max_length=100, blank=True)
    last_update = models.DateTimeField(null=True, blank=True)
    notified = models.ManyToManyField('self', blank=True, symmetrical=True, related_name='notify')
    last_notified = models.DateTimeField(blank=True)
    first_visit = models.BooleanField(default=True)
    votes = models.IntegerField(max_length=3, default=0)
    def __unicode__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

    def less_than_month(self):
        delta = datetime.datetime.now() - self.last_notified
        if delta.days < 30:
            return True
        else:
            return False

class FbookUser(models.Model):
    uid = models.BigIntegerField()
    name = models.CharField(max_length=50)
    def __unicode__(self):
        return self.name

class Like(models.Model):
    client = models.ForeignKey(Client, related_name='likez') 
    like = models.ForeignKey(FbookUser)
    rank = models.IntegerField(max_length=2)
    msg = models.CharField(max_length=500, blank = True)

    def __unicode__(self):
        return '%s likes %s' % (self.client, self.like.name)

STATUS_CHOICES = (
    (1,'Under Consideration'),
    (2,'In Progress'),
    (3,'Completed'),
    (4,'Rejected'),
)


class Suggestion(models.Model):
    client = models.ForeignKey(Client)
    title = models.CharField(max_length=100)
    suggestion = models.CharField(max_length=400)
    votes = models.IntegerField(max_length=4, default=0)
    status = models.IntegerField(max_length=1, choices = STATUS_CHOICES, default = 1)
    dev_comment = models.TextField()

    def __unicode__(self):
        return self.title

class Vote(models.Model):
    suggestion = models.ForeignKey(Suggestion)
    client = models.ForeignKey(Client)
    def __unicode__(self):
        return "%s for '%s'" % (str(self.client), str(self.suggestion))

class MatchStat(models.Model):
    num_matches = models.IntegerField(max_length=7)
    date = models.DateTimeField(auto_now_add=True)


#every client should be able to vote on     
#XXX User selects friends he/she is interested in (if possible) and submits form, the "interest" relationship is formed between that user and the other user (if possible..). Backend checks to see if that person is registered and if the person is, checks to see if the interest is mutual. 

#XXX Use rselects friends from list of ppl who hav app he/she is interested in. (harder to gain traction...). 


# Create your models here.

fbook/forms.py
from django.forms import ModelForm
from fbook.models import *
from django import forms

class SuggestionForm(ModelForm):
    suggestion = forms.CharField(widget=forms.Textarea(attrs={'rows':'10','cols':'70'}))
    class Meta:
        model = Suggestion
        fields = ('title','suggestion',)

class MessageForm(ModelForm):
    class Meta:
        model = Like
        fields = ('msg',)

class LikeForm(ModelForm):
    class Meta:
        model = Like
        fields = ('msg',)

class FbookUserForm(ModelForm):
    class meta:
        model = FbookUser
        fields = ('uid',)

templates/async.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>LikeEachOther</title>
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<link rel="stylesheet" href="/media/css/all.css" type="text/css" />
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.core.js"></script>
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.widget.js"></script>
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.position.js"></script>
<script type="text/javascript" src="/media/js/all.js"></script>
</head>
<body>


<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
      FB.init({appId: '{{app_id}}', status: true, cookie: true,
               xfbml: true});

    FB.api({method: 'fql.query', query: "{{query|safe}}"}, function(response) {
        window.ppl = response;
        var globaldata=[];
        var fids=[];
        for(i in response){
            globaldata.push(response[i].name); 
            fids.push(response[i].uid);
            };
        window.globaldata = globaldata;
        window.fids = fids;
    $("#example").autocomplete({source:globaldata});
    $("#example").watermark("Type the name of a Facebook friend:");
    updateNumber({{num_likes}});
    var table_len = {{num_likes}} + 1;
    $("#tbl1").tableDnD({
          onDrop: function(table, row) {
          updateRanks();
                  }
    });
    $("#rank").val(table_len.toString());
        });



      };
      (function() {
        var e = document.createElement('script'); e.async = true;
        e.src = document.location.protocol +
          '//connect.facebook.net/en_US/all.js';
        document.getElementById('fb-root').appendChild(e);
      }());

    
</script>


<h3 style="display:none">token: {{token}}</h3>
<div style="margin-left:auto;margin-right:auto;"><a href="/"><img src="/media/images/like.gif" alt="likeeachother" style="padding-bottom:10px;" /></a></div>
<div style="margin-bottom:25px;">
<p><b>What's the point?</b> The point is to findout if there is any mutual interest between friends on Facebook. If you want to date a friend, but don't want to risk losing your friendship, this app reduces that risk and removes any potential awkwardness in case the other person does not feel the same way.</p>
<br />
<p><b>What happens when I add someone I like?</b> First of all, the information will be kept private. Both you and the person you like will be notified <b>only if</b> you two like each other (you both must have LikeEachOther). If it is not mutual, <b>no one</b> will know or find out who you like.
</p>
<br />
<p><b>How do I get more people to use it?</b> Just <a class="lb" href="#" onclick="return tellPeople()">spread the word!</a></p>
</div> 
<div id="promote" style="display:none">
    <div class="head"><p>Not all of the people you like even have this app!</p></div>
    <div class="body"> <a href="#" class="myButton" onclick="return tellPeople()">Tell your friends</a></div>
</div>

{% if likes_tup %}
<div class="head">You currenty like <span id="num_likes"></span></div>
<div class="body">
<table id="tbl1">
<thead><th>Name</th><th>Rank</th><th>Has App</th><th>Remove</th></thead>
<tbody>
{% for like, has_app in likes_tup %}
<tr id="{{like.like.uid}}"><td>{{like.like.name}}</td><td>{{forloop.counter}}</td><td>{{has_app|yesno:"yes,no,maybe"}}</td><td><a href="#tbl1" class="myButton" onclick="return removePerson('{{like.like.uid}}')">Remove</a></td></tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}

<div class="head">Who are you interested in?</div>
<div class="body">
    <form style="margin-top:3px;" id="interest" action="{% url add_person %}" method="post">
    {% csrf_token %}
<fieldset>    <input style="display:inline" size="30" name="example" id="example" />
    <div style="display:inline" id="ppl">
       <input style="display:none" id="add_like_uid" name="add_like_uid" />
       <input style="display:none" id="add_like_name" name="add_like_name" />
       <input style="display:none" id="rank" name="rank" />

       <input style="display:inline" class="myButton" type="submit" value="Add" onclick="return changeValue()" />
    </div>    
    </fieldset>
    </form>   
{% for message in messages %}
<p style="color:red">{{message}}</p>
{% endfor %}
</div>

<div class="head">Your best match will notified at:</div>
<div class="body">
    <span id="old_email">{{email}} <a style="margin-left:10px;" href="#old_email" onclick="return showEmail()" class="myButton">Change</a></span> 
    <div id="change_email" style="display:none">Change to: <form action="{% url change_email %}" style="display:inline" method="post">{% csrf_token %}<input id="new_email" size="10" type="text" name="email"/> <input style="display:inline" class="myButton" type="submit" onclick="return validEmail()" value="Change"></form></div>
</div>

<div style="margin-top:40px;"><a class="footerlink" onclick="return showPrivacy()" href="#privacy">Privacy Policy</a> <a class="footerlink" onclick="return showTos()" href="#tos">Terms of Use</a> <a href="#delete-account" class="footerlink" onclick="return showDelete()">Delete My Account</a></div>
<div id="footer">
    <div id="privacy" style="display:none">We Like Each Other accesses your basic profile information and saves your facebook id along with the facebook id's of the people you like. None of this information will be used for other purposes or sold to any third parties. We hope you enjoy your experience!</div>
    <div id="tos" style="display:none">In order for this app to function properly, you agree to allow us to access your basic profile information and save both your facebook id and the id's of those you like. Furthermore, any attempts to misuse the application may result in denial of service. For instance, if you try and find out who likes you by improperly accessing information on our server, your account with our service may be terminated.</div>
    <div id="delete-account" style="display:none">
    <div class="head">If you delete your account, all the information regarding who you like will be deleted.</div>
    <div class="body"><form action="{% url delete_account %}" method="post" >{% csrf_token %} <input class="myButton" type="submit" value="Delete Account"></form></div>
    </div>
</div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{{app_name}}</title>
<link rel="stylesheet" href="/media/css/all2.css" type="text/css" />
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.core.js"></script>
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.widget.js"></script>
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.position.js"></script>
<script type="text/javascript" src="/media/js/qtip.js"></script>
<script type="text/javascript" src="/media/js/all2.js"></script>
{% block extra_head %}
{% endblock extra_head %}
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-12460479-17']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
{% block fbdiv %}
{% endblock fbdiv %}
{% include "logo.html" %}
<br />
<div id="about" style="display:none">
{% include "about.html" %}
</div>

{% include "links.html" %}

{% block about %}
{% endblock %}

<div id="loading">
<center><img src="/media/images/ajax-loader.gif" /> 
<p>loading data from Facebook :(</p>
</center>
</div>


<div id="wrapper" style="display:none">
{% block content %}

{% endblock %}
</div>

{% block footer %}

{% endblock %}

{% block js %}
{% endblock %}
</body>
</html>

templates/comments.html
{% extends "base.html" %}
{% block extra_head %}
<script type="text/javascript" src="/media/js/suggestion.js"></script>
<script>
$(document).ready(function() {

// get current number of characters
$('#title_count').html($('#id_title').val().length + ' characters');

$('#id_title').keyup(function() {
    // get new length of characters
    $('#title_count').html($(this).val().length + ' characters');
});

$('#suggestion_count').html($('#id_suggestion').val().length + ' characters');

$('#id_suggestion').keyup(function() {
    // get new length of characters
    $('#suggestion_count').html($(this).val().length + ' characters');
});

$.fn.qtip.styles.mystyle = { 
   width: 200,
   color: 'black',
   border: {
      radius: 5,
   },
   tip: 'topMiddle',
    name: 'blue'
};

    {% for s in suggestions %}
        $("tbody tr:nth-child({{forloop.counter}})").qtip({
            content: '{{s.suggestion}}', 
            show: 'mouseover',
            hide: 'mouseout',
            style: 'mystyle', 
            position: { corner: { target: 'bottomMiddle', tooltip: 'topMiddle' } }    
        });
    {% endfor %}
$("#loading").hide();
$("#wrapper").show();
});


</script>
{% endblock %}

{% block content %}
<div class="head">Vote on suggestions</div>
<div class="body">
{% if suggestions %}
<table id="tbl1">
<thead><th style="">Suggestion</th><th>Votes</th><th>Upvote</th><th>Admin Comments</th></thead>
<tbody>
{% for s in suggestions %}
<tr><td>{{s.title}}</td> <td id="{{s.id}}">{{s.votes}}</td><td><a href="#" onclick="return upvote({{s.id}})"><img src="/media/images/1.gif" /></a></td><td>{% firstof s.dev_comment "n/a" %}</td></tr>
{% endfor %}
</tbody>
</table>
{% else %}
<center>There are no suggestions right now.</center>
{% endif %}
</div>
<div class="head">
Do you have a suggestion not listed above?
</div>
<div class="body">
<form action="" method="post"> {% csrf_token %}
<p style="font-weight:bold">Title of your suggestion</p> {{form.title}} {{form.title.errors}} 
<p><span id="title_count"></span><span> (100 max)</span></p>
<p style="font-weight:bold;margin-top:10px;">Full description of your suggestion and reasons why it should be implemented</p> {{form.suggestion}} {{form.suggestion.errors}}
<p> <span id="suggestion_count"></span><span> (400 max)</span></p>
<div style="margin:15px;"></div>
<input type="submit" style="display:block" value="Add Suggestion" class="myButton" />
</form>
</div>
{% endblock %}

{% block footer %}
{% include "footer_normal.html" %}
{% endblock %}

templates/delete_account.html
    <div class="head">If you delete your account, all the information regarding who you like will be deleted.</div>
    <div class="body"><form action="{% url delete_account %}" method="post" >{% csrf_token %} <input class="myButton" type="submit" value="Delete Account"></form></div>

templates/footer_updating.html
<div style="margin-top:40px;"><a class="footerlink" onclick="return showPrivacy()" href="#privacy">Privacy Policy</a> <a class="footerlink" onclick="return showTos()" href="#tos">Terms of Use</a> </div>
<div id="footer">
    <div id="privacy" style="display:none">By authorizing this application, you grant {{app_name}} access to your basic profile information and email address. None of this information will be used for other purposes or sold to any third parties.</div>
    <div id="tos" style="display:none">In order for this app to function properly, you agree to allow us to access your basic profile information and email address.  Furthermore, any attempts to abuse the application may result in loss of access to your {{app_name}} account.</div>
</div>

templates/links.html
<div id="about_link">
<p> <a href="#" onclick="showAbout()">how it works</a> |  <a href="/" id="mylikes">my likes</a> | <a id="rf" href="{% url request_features %}">suggest features and vote</a> | <a href="#" id="contact">questions?</a></p>
</div> 

templates/logo.html
<div style="margin-left:auto;margin-right:auto;"><a href="/"><img src="/media/images/wootmatch2.jpg" alt="likeeachother" style="padding-bottom:10px;" /></a>
<img style="position:relative;top:-10px;" src="/media/images/getmatched.gif" />
</div>

templates/main.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>LikeEachOther</title>
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<link rel="stylesheet" href="/media/css/all.css" type="text/css" />
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.core.js"></script>
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.widget.js"></script>
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.position.js"></script>
<script type="text/javascript" src="/media/js/all.js"></script>
</head>
<body>


<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
      FB.init({appId: '{{app_id}}', status: true, cookie: true,
               xfbml: true});

    FB.api({method: 'fql.query', query: "{{query|safe}}"}, function(response) {
        window.ppl = response;
        var globaldata=[];
        var fids=[];
        for(i in response){
            globaldata.push(response[i].name); 
            fids.push(response[i].uid);
            };
        window.globaldata = globaldata;
        window.fids = fids;
    $("#example").autocomplete({source:globaldata});
    $("#example").watermark("Type the name of a Facebook friend:");
    updateNumber({{num_likes}});
    var table_len = {{num_likes}} + 1;
    $("#tbl1").tableDnD({
          onDrop: function(table, row) {
          updateRanks();
                  }
    });
    $("#rank").val(table_len.toString());
        });



      };
      (function() {
        var e = document.createElement('script'); e.async = true;
        e.src = document.location.protocol +
          '//connect.facebook.net/en_US/all.js';
        document.getElementById('fb-root').appendChild(e);
      }());

    
</script>


<h3 style="display:none">token: {{token}}</h3>
<div style="margin-left:auto;margin-right:auto;"><a href="/"><img src="/media/images/like.gif" alt="likeeachother" style="padding-bottom:10px;" /></a></div>
<div style="margin-bottom:25px;">
<p><b>What's the point?</b> The point is to findout if there is any mutual interest between friends on Facebook. If you want to date a friend, but don't want to risk losing your friendship, this app reduces that risk and removes any potential awkwardness in case the other person does not feel the same way.</p>
<br />
<p><b>What happens when I add someone I like?</b> First of all, the information will be kept private. Both you and the person you like will be notified <b>only if</b> you two like each other (you both must have LikeEachOther). If it is not mutual, <b>no one</b> will know or find out who you like.
</p>
<br />
<p><b>How do I get more people to use it?</b> Just <a class="lb" href="#" onclick="return tellPeople()">spread the word!</a></p>
</div> 
<div id="promote" style="display:none">
    <div class="head"><p>Not all of the people you like even have this app!</p></div>
    <div class="body"> <a href="#" class="myButton" onclick="return tellPeople()">Tell your friends</a></div>
</div>

{% if likes_tup %}
<div class="head">You currenty like <span id="num_likes"></span></div>
<div class="body">
<table id="tbl1">
<thead><th>Name</th><th>Rank</th><th>Has App</th><th>Remove</th></thead>
<tbody>
{% for like, has_app in likes_tup %}
<tr id="{{like.like.uid}}"><td>{{like.like.name}}</td><td>{{forloop.counter}}</td><td>{{has_app|yesno:"yes,no,maybe"}}</td><td><a href="#tbl1" class="myButton" onclick="return removePerson('{{like.like.uid}}')">Remove</a></td></tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}

<div class="head">Who are you interested in?</div>
<div class="body">
    <form style="margin-top:3px;" id="interest" action="{% url add_person %}" method="post">
    {% csrf_token %}
<fieldset>    <input style="display:inline" size="30" name="example" id="example" />
    <div style="display:inline" id="ppl">
       <input style="display:none" id="add_like_uid" name="add_like_uid" />
       <input style="display:none" id="add_like_name" name="add_like_name" />
       <input style="display:none" id="rank" name="rank" />

       <input style="display:inline" class="myButton" type="submit" value="Add" onclick="return changeValue()" />
    </div>    
    </fieldset>
    </form>   
{% for message in messages %}
<p style="color:red">{{message}}</p>
{% endfor %}
</div>

<div class="head">Your best match will notified at:</div>
<div class="body">
    <span id="old_email">{{email}} <a style="margin-left:10px;" href="#old_email" onclick="return showEmail()" class="myButton">Change</a></span> 
    <div id="change_email" style="display:none">Change to: <form action="{% url change_email %}" style="display:inline" method="post">{% csrf_token %}<input id="new_email" size="10" type="text" name="email"/> <input style="display:inline" class="myButton" type="submit" onclick="return validEmail()" value="Change"></form></div>
</div>

<div style="margin-top:40px;"><a class="footerlink" onclick="return showPrivacy()" href="#privacy">Privacy Policy</a> <a class="footerlink" onclick="return showTos()" href="#tos">Terms of Use</a> <a href="#delete-account" class="footerlink" onclick="return showDelete()">Delete My Account</a></div>
<div id="footer">
    <div id="privacy" style="display:none">We Like Each Other accesses your basic profile information and saves your facebook id along with the facebook id's of the people you like. None of this information will be used for other purposes or sold to any third parties. We hope you enjoy your experience!</div>
    <div id="tos" style="display:none">In order for this app to function properly, you agree to allow us to access your basic profile information and save both your facebook id and the id's of those you like. Furthermore, any attempts to misuse the application may result in denial of service. For instance, if you try and find out who likes you by improperly accessing information on our server, your account with our service may be terminated.</div>
    <div id="delete-account" style="display:none">
    <div class="head">If you delete your account, all the information regarding who you like will be deleted.</div>
    <div class="body"><form action="{% url delete_account %}" method="post" >{% csrf_token %} <input class="myButton" type="submit" value="Delete Account"></form></div>
    </div>
</div>
</body>
</html>

templates/privacy.html
<html>
<head>
</head>
<body>
<h1 id="">Privacy Policy</h1>
<p>We Like Each Other accesses your basic profile information and saves your facebook id along with the facebook id's of the people you like. None of this information will be used for other purposes or sold to any third parties. We hope you enjoy your experience!</p>
</body>
</html>

templates/sync_new.html
{% extends "base.html" %}
{% block extra_head %}
<script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script>
{% endblock %}

{% block fbdiv %}
<div id="fb-root"></div>
<h3 style="display:none">token: {{token}}</h3>
{% endblock %}

{% block about %}
<div id="about" style="{% if not first_visit %}display:none{% endif %}">
{% include "about.html" %}
</div>
{% endblock %}


{% block content %}
<div style="display:none" id="extra">
<div class="head" id="extra_title">
</div>
<div class="body">
<input style="display:inline" size="50" name="personal_msg" id="personal_msg" />
<input id="msg_id" type="hidden" />
<button onclick="return sendPersonalMsg()" class="myButton">Submit</button>
<button onclick="return hideExtra()" class="myButton">Cancel</button>

</div>
</div>

<div id="tbl_container"{% if not likes_tup %} style="display:none"{% endif %}>
<div class="head">You currenty like <span id="num_likes"></span></div>
<div class="body">
<table id="tbl1">
<thead><th>Name</th><th id="tbl_rank">Rank</th><th>Has App</th><th id="tbl_msg">Message</th><th>Remove</th></thead>
<tbody>
{% if likes_tup %}
{% for like, has_app in likes_tup %}
<tr id="{{like.like.uid}}"><td>{{like.like.name}}</td><td>{{forloop.counter}}</td><td>{{has_app|yesno:"yes,no,maybe"}}</td><td id="msg{{forloop.counter}}">{% if like.msg %}<a href="#" class="lb" onclick="return editMessage('{{like.like.uid}}')">yes</a>{% else %}<a href="#" class="lb" onclick="return showCreateMsg('{{like.like.uid}}')">create</a> {% endif %}</td>
<td><a href="#tbl1" class="myButton" onclick="return removePerson('{{like.like.uid}}')">Remove</a></td></tr>
{% endfor %}
{% endif %}
</tbody>
</table>
</div>
</div>

<div class="head">Who are you interested in?</div>
<div class="body">
<fieldset id="autocomplete" style="display:inline">    <input style="display:inline" size="30" name="example" id="example" />
 <a href="#" style="display:inline" class="myButton" onclick="return addLikeAuto()">Add</a>
<span style="dispay:inline;padding-left:20px;"> not working? <a href="#" class="lb" onclick="switchForm()">try this</a> or <a href="/" class="lb">refresh</a></span>
</fieldset>
<fieldset id="normal" style="display:none">
<select id="friends">

 </select>
<a href="#" class="myButton" onclick="return addLikeNormal()">Add</a>
</fieldset>      
</div>
<div class="head">Your best match will notified at:</div>
<div class="body">
    <span id="old_email">{{email}}<a style="margin-left:10px;" href="#old_email" onclick="return showEmail()" class="myButton">Change</a></span> 
    <div id="change_email" style="display:none">Change to: <form action="{% url change_email %}" style="display:inline" method="post">{% csrf_token %}<input id="new_email" size="10" type="text" name="email"/> <input style="display:inline" class="myButton" type="submit" onclick="return validEmail()" value="Change"></form></div>
</div>

{% endblock %}

{% block footer %}
{% include "footer_normal.html" %}
{% endblock %}

{% block js %}
<script type="text/javascript">
var got_response = false;

while(! got_response){
  FB.init({
    appId  : '{{app_id}}',
    status : true, // check login status
    cookie : true, // enable cookies to allow the server to access the session
    xfbml  : true  // parse XFBML
  });


    FB.api({method: 'fql.query', query: "{{query|safe}}"}, function(response) {

        try {
            window.response = response.sort(function(a,b) {

            var n1 = a.name.toLowerCase();
            var n2 = b.name.toLowerCase();
            if (n1 < n2) {return  -1}
            else {return 1} 
            });
            got_response = true;
            alert('got response...');
            }   
        catch(error) {got_response = false; alert('couldnt sort response'); }
    })
};

        window.ppl = window.response;
        var globaldata=[];
        var fids=[];
        div=document.getElementById("ppl");
        for(i in response){
            globaldata.push(window.response[i].name); 
            fids.push(window.response[i].uid);
            };
        $("#example").autocomplete({source:globaldata});
        $("#example").watermark("Type the name of a Facebook friend:");
        window.globaldata = globaldata;
        window.fids = fids;
    $("#tbl1").tableDnD({
          onDrop: function(table, row) {
            updateRanks();
          }
    });
updateNumber();
$("#loading").hide();
$("#wrapper").show();
</script>
{% endblock %}

templates/tos.html
<html>
<head>
</head>
<body>
<h1 id="">Terms of Service</h1>
<p>In order for this app to function properly, you agree to allow us to access your basic profile information and save both your facebook id and the id's of those you like. Furthermore, any attempts to misuse the application may result in denial of service. For instance, if you try and find out who likes you by improperly accessing information on our server, your account with our service may be terminated. </p>
</body>
</html>

templates/updating.html
{% extends "base.html" %}

{% block content %}
<div class="head">Matching is in progress!</div>
<div class="body">You will not be able to update your ranking or add people you like during this time. Please check back to see if matching has finished!</div>
{% endblock %}

{% block footer %}
{% include "footer_updating.html" %}
{% endblock %}

{% block js %}
<script>
$(document).ready(function() {
$("#loading").hide();
$("#wrapper").show();
});
</script>
{% endblock %}